version: '3.8'

services:
  app:
    build: .
    container_name: suivi-compte
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:/app/data/dev.db
    volumes:
      - ./data:/app/data
    restart: always
